### ISSUE TITLE
考虑加入axios库吗

### ISSUE THREAD

**Issue by honwhy** [mefengl/wxt-starter#3]
考虑加入axios库吗

**Comment by mefengl** [comment]
不会，没看到什么必要性

**Comment by mefengl** [comment]
不太可能。你认为它的好处在哪里？

扩展 fetch 调用的情况应该比较少。如果只是升级 fetch，我会想到使用 ofetch，但好像没这个必要。

**Comment by honwhy** [comment]
感谢，我可以试试ofetch
